apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-pressurecooker
spec:
  selector:
    matchLabels:
      app: kubernetes-pressurecooker
  template:
    metadata:
      labels:
        app: kubernetes-pressurecooker
    spec:
      serviceAccountName: kubernetes-pressurecooker
      containers:
      - name: kubernetes-pressurecooker
        image: decastroandres/kubernetes-pressurecooker:latest
        args: [
          "--node-name=kind-control-plane"
        ]
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
